server:
  port: 8081

spring:
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-004
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        embeddings-path: /embeddings
      api-key: AIzaSyCdLcucHHGAWQ5gMTKcN4-xbCfI1OFY_pU

  datasource:
    url: jdbc:postgresql://docker.host.internal:5432/nexus
    username: admin
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

management:
  endpoint:
    configprops:
      show-values: always
      access: unrestricted
    env:
      show-values: always
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
    access:
      default: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: http://docker.host.internal:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka, http://host.docker.internal:8762/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5

logging:
  level:
    root: debug
    web: debug