server:
  port: 8081

spring:
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-004
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        embeddings-path: /embeddings
      api-key: AIzaSyCdLcucHHGAWQ5gMTKcN4-xbCfI1OFY_pU
    mcp:
      server:
        name: nexus-mcp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/nexus
    username: admin
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
    access:
      default: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: http://zipkin:9411/api/v2/spans
