server:
  port: 8081

spring:
  ai:
    mcp:
      enabled: true
    openai:
      embedding:
        options:
          model: text-embedding-004
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        embeddings-path: /embeddings
      api-key: AIzaSyCdLcucHHGAWQ5gMTKcN4-xbCfI1OFY_pU
  datasource:
    url: jdbc:postgresql://postgres:5432/nexus
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

management:
  endpoint:
    configprops:
      show-values: always
      access: unrestricted
    env:
      show-values: always
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
    access:
      default: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: http://host.docker.internal:9411/api/v2/spans
logging:
  level:
    root: debug
    web: debug