server:
  port: 8080

management:
  prometheus.metrics.export.enabled: true
  endpoints:
    show-values: ALWAYS
    web.exposure:
      include: "*"
      health:
        show-details: always
        show-components: always
  endpoint:
    configprops:
      show-values: always
      access: unrestricted
    env:
      show-values: always
      access: unrestricted
    metrics.tags.application: ${spring.application.name}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: nexus
              uri: lb://nexus
              predicates:
                - Path=/nexus/**
            - id: ai
              uri: lb://ai
              predicates:
                - Path=/ai/**
            - id: config
              uri: lb://config
              predicates:
                - Path=/config/**
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          metrics:
            enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-1:8761/eureka/,http://eureka-2:8761/eureka/,http://eureka-3:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    initial-instance-info-replication-interval-seconds: 0

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
