server:
  port: 8082

spring:
  ai:
    openai:
      api-key: AIzaSyA1uhQ2iUXAaoW7lY7-wHH-rTWvNByt7Tk
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemma-3n-e4b-it
        completions-path: /chat/completions
      embedding:
        options:
          model: text-embedding-004
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        api-key: AIzaSyA1uhQ2iUXAaoW7lY7-wHH-rTWvNByt7Tk
        embeddings-path: /embeddings

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true
    healthcheck:
      enabled: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}