server:
  port: 8082

spring:
  ai:
    mcp:
      client:
        sse:
          connections:
            nexus-mcp:
              url: http://nexus:8081
    openai:
      api-key: AIzaSyCdLcucHHGAWQ5gMTKcN4-xbCfI1OFY_pU
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.0-flash-lite
        completions-path: /chat/completions
      embedding:
        options:
          model: text-embedding-004
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        api-key: AIzaSyCdLcucHHGAWQ5gMTKcN4-xbCfI1OFY_pU
        embeddings-path: /embeddings

management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
    access:
      default: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: http://zipkin:9411/api/v2/spans
