server:
  port: 8082

spring:
  ai:
    openai:
      api-key: AIzaSyCdLcucHHGAWQ5gMTKcN4-xbCfI1OFY_pU
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.0-flash-lite
        completions-path: /chat/completions
      embedding:
        options:
          model: text-embedding-004
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        api-key: AIzaSyCdLcucHHGAWQ5gMTKcN4-xbCfI1OFY_pU
        embeddings-path: /embeddings

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

mcp:
  server:
    base-url: gateway:8080/nexus
