server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false